name: Node.js CI

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies in code directory
        run: |
          cd code
          npm ci
      - name: Install dependencies in services/ethereum directory
        run: |
          cd services/ethereum
          npm ci
      - name: Build code directory
        run: |
          cd code
          npm run build --if-present
      - name: Test code directory
        run: |
          cd code/services/ethereum/test
          npx hardhat test
      # Optionally, add build or test commands for services/ethereum if needed