name: LaTeX Build

on:
  push:
    branches:
      - prototype # Adjust this to your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy assets
        run: cp -r ./docs/project-proposal/assets/* ./docs/project-proposal # Adjust the path as needed

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: project-proposal.tex # Replace with your main LaTeX file name
          working_directory: ./docs/project-proposal # Set to the directory containing your LaTeX files
          extra_system_packages: "inkscape" # Install additional packages if needed

